### PR TITLE
Follow node convention passing stderr before stdout

### PR DESCRIPTION
**Pull request by jstewmon**
This is a nifty module.  I was doing a bunch of custom cli work to interact with git and make in a project, and procstreams proved to be a useful replacement, allowing me to delete a bunch of code.  I love deleting code!

But, I use the excellent async module to organize my callbacks.  I usually just send the stderr and stdout to the async task callback.  That callback follows the node convention of expecting the first parameter to contain any errors.  So, to use procstreams with it, I have to do something like this:

``` javascript
var dataSwapArgs = function(callback) {
  return function(stdout, stderr) {
    callback(stderr, stdout);
  };
};
async.auto({
  locals: function(callback) {
    proc('git', [
      'for-each-ref',
      '--format={"objectname": "%(objectname:short)", "refname": "%(refname:short)", "upstream":"%(upstream:short)"}',
      'refs/heads'
    ], gitProcOptions).data(dataSwapArgs(callback));
  }
}, function(err, results) {
  if(err) { console.error(err); }
  else {
    //...
  }
});
```

This pull request changes the order of the arguments when _output is emitted.  By passing stderr before stdout for the data method, the async task callback can be passed directly to the data method.

### CODE REVIEW

**Comment by polotek** [comment]
stderr is not an error object, it's the error output from the process. In that sense it's not exactly the same as The node convention of "first arg is an error". Output on stderr doesn't necessarily indicate an error in the process. That said, I can see your use case being common. The problem with switching is that the data method kind of follows the child_process.exec signature. Except there's no err object at the beginning. Maybe we should do that instead just to be consistent with something. And then perhaps add an option that will make your case simpler.

Let me think about it a little. I'm open to other suggestions arguments as well.

**Comment by polotek** [comment]
Also, don't check node_modules into git. Not recommended for libraries.

**Comment by jstewmon** [comment]
Er, sorry about the modules - I'm stuck in the habit of doing it for my applications.

I see what you mean about the error object being different than stderr having content.  That's an important distinction.

Updating the signature of data to be consistent with the callback signature for exec would certainly work (that's what I was using previously).

**Comment by jstewmon** [comment]
It occurred to me that my problem can be solved by having a method that is mutually exclusive with data, and is only called in case there is an error running the child process.

Sorry for being so chatty on this issue.

**Comment by polotek** [comment]
So this is on my roadmap as well. The idea is that if the child process returns a non-zero status code, then it failed. You can still check this by hooking onto the "exit" event, but i think it'll be a good idea to surface it in data as well.

```
$p('run_it').data(function(err, stdout, stderr) {
  // if the proc existed with non-zero status, this object will hold any information, otherwise it's null
  if(err) {
    // err.code - status code from proc
    // err.signal - a signal that caused the proc to exit
  }
})
```

I'm also looking for a better name than `data` for this function. What do you think?

**Comment by jstewmon** [comment]
I considered the exit event, but it is more cumbersome to collect the contents of stderr using the exit event since its callback is only passed the code and signal.

I suggested having a separate error method because it would make the API a little more expressive, especially if you consider renaming data to something like 'complete', 'success' or 'done'.

But, I think it would be fine for data to match the signature of exec.  Implementers can check the first argument for an error without much fuss.  In this case, I think 'complete' or 'done' would be ok names for what is currently 'data'.

The more I think about it, the more I like 'done' for what is currently 'data'.  Those other names are too long.

**Comment by polotek** [comment]
I am going to surface an "error" event. That's on the roadmap too. But that
needs to be in combination with the data() call. The data() call is
optional, and the real benefit of it is that the output of stdout/stderr is
collected for you. This doesn't happen at all if you don't set a callback
with data(). Whatever the name is should still convey that you're getting
the collected output of the process. Maybe that's not so important and
done() is fine. I'll poll some other people.

Thanks for the feedback. I think we are moving in the right direction. I'm
gonna leave this ticket open to remind me to fix this.

On Fri, Jan 27, 2012 at 2:56 PM, Jonathan Stewmon <
reply@reply.github.com

> wrote:
> 
> I considered the exit event, but it is more cumbersome to collect the
> contents of stderr using the exit event since its callback is only passed
> the code and signal.
> 
> I suggested having a separate error method because it would make the API a
> little more expressive, especially if you consider renaming data to
> something like 'complete', 'success' or 'done'.
> 
> But, I think it would be fine for data to match the signature of exec.
>  Implementers can check the first argument for an error without much fuss.
>  In this case, I think 'complete' or 'done' would be ok names for what is
> currently 'data'.
> 
> The more I think about it, the more I like 'done' for what is currently
> 'data'.  Those other names are too long.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/polotek/procstreams/pull/5#issuecomment-3695758

## 

Marco Rogers
marco.rogers@gmail.com | https://twitter.com/polotek

Life is ten percent what happens to you and ninety percent how you respond
to it.
- Lou Holtz

**Comment by polotek** [comment]
I've implemented the things we talked about. Have a look.

54a03b2
8c4cd24

Sorry I couldn't give you credit for this pull request. In the future I'll do things different so I make changes on top of your commits. Thanks.

**Pull request closed without merging**
